-- Migration 0010: Partition events table (by received_at) + dedup lookup index + engagement counters
-- HAND-WRITTEN: drizzle-kit cannot produce partitioning DDL.
-- Drizzle schema files describe the final column state; this migration achieves it
-- via DROP+CREATE for events (partitioned) and ALTER for contacts.
-- The snapshot (meta/0010_snapshot.json) was generated by drizzle-kit from the TS
-- schema changes and remains valid - it describes column state, not partitioning.
--
-- PRECONDITION: events table is empty. This migration is DESTRUCTIVE on the events
-- table. Verify SELECT count(*) FROM events = 0 before applying.

-- Step 1: Drop FK from contact_conflicts that references events(id)
-- (Cannot exist after partitioning: PK becomes (id, received_at) and a FK on
-- event_id alone has no matching unique index on the partitioned table.)
-- IF EXISTS: the table/constraint may not exist in all database instances
-- (e.g., the seed test DB was initialized before contact_conflicts was added).
ALTER TABLE IF EXISTS "contact_conflicts" DROP CONSTRAINT IF EXISTS "contact_conflicts_event_id_events_id_fk";
--> statement-breakpoint

-- Step 2: Drop FK constraints on the events table itself
ALTER TABLE "events" DROP CONSTRAINT "events_tenant_id_tenants_id_fk";
--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "events_contact_id_contacts_id_fk";
--> statement-breakpoint

-- Step 3: Drop the old (plain) events table and all its indexes
DROP TABLE "events";
--> statement-breakpoint

-- Step 4: Create events as a partitioned table (partition key: received_at)
-- Real PK is (id, received_at) because Postgres requires partition key in PK.
-- Drizzle schema says .primaryKey() on id alone - representational limitation
-- documented in drizzle/schema/events.ts and CLAUDE.md spec invariants.
CREATE TABLE "events" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "contact_id" uuid NOT NULL,
  "type" text NOT NULL,
  "event_name" text,
  "properties" jsonb,
  "context" jsonb,
  "message_id" text,
  "timestamp" timestamp with time zone NOT NULL,
  "received_at" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("id", "received_at")
) PARTITION BY RANGE ("received_at");
--> statement-breakpoint

-- Step 5: Create partitions (6 months: Jul 2026 - Dec 2026, NO DEFAULT)
-- A missing partition causes a loud INSERT error - desired alerting signal.
-- Partition creation is maintained by a scheduled check in the scan tick.
CREATE TABLE events_y2026m07 PARTITION OF events
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
--> statement-breakpoint
CREATE TABLE events_y2026m08 PARTITION OF events
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
--> statement-breakpoint
CREATE TABLE events_y2026m09 PARTITION OF events
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
--> statement-breakpoint
CREATE TABLE events_y2026m10 PARTITION OF events
  FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
--> statement-breakpoint
CREATE TABLE events_y2026m11 PARTITION OF events
  FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
--> statement-breakpoint
CREATE TABLE events_y2026m12 PARTITION OF events
  FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
--> statement-breakpoint

-- Step 6: Recreate indexes (partitioned indexes - auto-created per partition)
CREATE INDEX "idx_events_contact_time"
  ON "events" USING btree ("contact_id", "timestamp" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX "idx_events_tenant_name"
  ON "events" USING btree ("tenant_id", "event_name", "timestamp" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX "idx_events_tenant_time"
  ON "events" USING btree ("tenant_id", "timestamp" DESC NULLS LAST);
--> statement-breakpoint

-- Step 7: Dedup lookup index (non-unique; enforcement via advisory lock in ingest)
CREATE INDEX "idx_events_dedup_lookup"
  ON "events" USING btree ("tenant_id", "message_id")
  WHERE "message_id" IS NOT NULL;
--> statement-breakpoint

-- Step 8: FK constraints (from partitioned table to other tables - works in PG 12+)
ALTER TABLE "events" ADD CONSTRAINT "events_tenant_id_tenants_id_fk"
  FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_contact_id_contacts_id_fk"
  FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id")
  ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

-- Step 9: Engagement counter columns on contacts
ALTER TABLE "contacts" ADD COLUMN "event_count_bucket_current" integer DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "event_count_bucket_prev" integer DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "last_counter_reset_at" timestamp with time zone;
