/**
 * KB context builder - KB search half of Phase 3 exit criteria.
 *
 * This is NOT task 23 (auto-crawl). It is the similarity search path that
 * wires existing embeddings into the content generation context packet.
 * Task numbering: this work sits between task 22 (embeddings) and task 23
 * (auto-crawl) and is referenced in §11 Phase 3 exit criteria.
 *
 * [impl] Query text: the step's brain_instruction concatenated with the
 * action_type, separated by ": ". The action_type is always present (defaults
 * to "nurture_value" in the assembler), so the query is never empty when
 * brain_instruction is absent. Contact behavior (event names, lifecycle state)
 * is deliberately excluded: event names are a product-specific vocabulary that
 * does not share a semantic space with knowledge base prose. Example: an event
 * named "project_created" will not match a KB entry about "billing FAQ"
 * meaningfully. The brain_instruction + action_type describes what the email
 * step is about, which IS the same semantic space as the KB entries.
 *
 * [impl] Explicit kb_ref beats similarity. If the compiled plan step carries
 * a kb_ref, that entry is always included (fetched by title, case-sensitive,
 * tenant-scoped) regardless of its cosine similarity score. The remaining
 * slots (up to KB_MAX_RESULTS total) are filled by similarity search. If the
 * kb_ref entry is not found or has no embedding, it is silently omitted; the
 * similarity results fill all slots instead.
 *
 * [impl] Retrieval parameters - unvalidated starting values, recorded here
 * for calibration:
 *   KB_MAX_RESULTS = 3  (max entries returned; start conservatively)
 *   KB_SIMILARITY_FLOOR = 0.70  (cosine similarity threshold 0..1; unvalidated)
 *
 * Both are named constants so they can be adjusted without touching logic.
 * Similarity scores of retrieved and rejected entries are logged at debug
 * level so they can be monitored against real data and these constants
 * calibrated later.
 *
 * [impl] Model consistency: the query vector MUST be generated by the same
 * model used to generate the stored entry vectors. If a tenant changes their
 * embedding_model in llm_configs, entries embedded with the old model become
 * incomparable to queries using the new model. Today nothing detects this:
 * the old vectors are still present and will be ranked by cosine distance
 * against the new-model query, producing meaningless results rather than
 * an error. This is a silent correctness hazard. See docs/BACKLOG.md
 * "KB embedding model change" for the tracking item.
 *
 * [impl] Embedding API call cost: every message that reaches content
 * generation now incurs one embedding API call for the KB query. This call
 * uses the same provider (baseUrl + apiKey + embeddingModel) as the entry
 * indexing. The query text (brain_instruction + action_type) is the same for
 * all contacts on the same flow step, which means the query vector is
 * identical across contacts. At MVP scale (small tenant, few contacts per
 * step) this is immaterial. At scale, a per-step query cache keyed on
 * (tenant_id, flow_id, step_order, embedding_model) would eliminate redundant
 * API calls entirely. See docs/BACKLOG.md "KB query vector cache" for the
 * tracking item. No cache is built here.
 *
 * Mirror side: PUBLIC (packages/worker is mirrored).
 */
import { sql } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import {
  resolveEmbeddingProvider,
  callEmbedding,
  recordEmbeddingUsage,
  EmbeddingPermanentError,
} from "./embedding-client.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Db = NodePgDatabase<Record<string, never>>;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Maximum number of KB entries to include in the context packet.
 * Unvalidated starting value - calibrate against real data.
 * Kept low to limit token budget pressure on the context.
 */
export const KB_MAX_RESULTS = 3;

/**
 * Minimum cosine similarity score for an entry to be included.
 * Range 0..1 (0 = orthogonal, 1 = identical). 0.70 is a conservative start.
 * Entries at or above this threshold are "relevant"; below are "weak matches".
 * Calibrate by observing logged similarity scores against real knowledge bases.
 */
export const KB_SIMILARITY_FLOOR = 0.70;

// ---------------------------------------------------------------------------
// buildKbContextSection
// ---------------------------------------------------------------------------

/**
 * Build the kb_context string for the draft prompt.
 *
 * Steps:
 * 1. Resolve the tenant's embedding provider.
 * 2. Embed the query text (brain_instruction + action_type).
 * 3. If the step carries an explicit kb_ref, fetch that entry by title.
 * 4. Fill remaining slots with similarity search results.
 * 5. Format and return the combined context string.
 *
 * Graceful degradation:
 * - If provider resolution fails, return undefined (no KB context; message
 *   proceeds without it). This is a soft failure: the embedding was already
 *   indexed before this point; a configuration issue here degrades quality
 *   but does not block the message.
 * - If the similarity query fails, return undefined (same reasoning).
 * - If no entries meet the floor, return undefined (no section emitted rather
 *   than an empty-looking "KNOWLEDGE BASE CONTEXT:" block).
 * - An undefined kb_context is indistinguishable from the pre-task-22 state
 *   as far as the draft prompt is concerned (the field was always optional).
 *
 * @param db            - Drizzle database instance.
 * @param tenantId      - Tenant scope (entries from other tenants are excluded).
 * @param queryText     - The text to embed for similarity search
 *                        (brain_instruction + ": " + action_type).
 * @param kbRef         - Optional explicit entry title from the compiled step.
 *                        If provided, that entry is always included.
 * @param maxResults    - Max entries to return (default KB_MAX_RESULTS).
 * @param similarityFloor - Min cosine similarity (default KB_SIMILARITY_FLOOR).
 * @returns Formatted string for DraftPromptContext.kb_context, or undefined if
 *          no relevant entries are found or the query fails.
 */
export async function buildKbContextSection(
  db: Db,
  tenantId: string,
  queryText: string,
  kbRef?: string,
  maxResults: number = KB_MAX_RESULTS,
  similarityFloor: number = KB_SIMILARITY_FLOOR,
): Promise<string | undefined> {
  // 1. Resolve the tenant's embedding provider.
  const providerResult = await resolveEmbeddingProvider(db, tenantId);
  if (!providerResult.ok) {
    // Config issue - degrade gracefully, no KB context this message.
    console.warn(
      `[context-kb] cannot build KB context for tenant ${tenantId}: ` +
        `${providerResult.reason}. Proceeding without KB context.`,
    );
    return undefined;
  }

  const { apiKey, baseUrl, embeddingModel } = providerResult;

  // 2. Generate the query embedding.
  let queryVector: number[];
  try {
    queryVector = await callEmbedding(baseUrl, apiKey, embeddingModel, queryText);
    await recordEmbeddingUsage(db, tenantId, providerResult, queryText, true);
  } catch (err) {
    await recordEmbeddingUsage(db, tenantId, providerResult, queryText, false);
    // Any embedding failure (transient or permanent) = no KB context this message.
    // This is soft: a failed query does not block the message.
    const msg = err instanceof Error ? err.message : String(err);
    const kind = err instanceof EmbeddingPermanentError ? "permanent" : "transient";
    console.warn(
      `[context-kb] ${kind} error embedding query for tenant ${tenantId}: ` +
        `${msg}. Proceeding without KB context.`,
    );
    return undefined;
  }

  // 3. Resolve the explicit kb_ref entry (if any).
  let pinnedEntry: KbEntry | undefined;
  if (kbRef) {
    pinnedEntry = await fetchByTitle(db, tenantId, kbRef);
    if (!pinnedEntry) {
      console.warn(
        `[context-kb] kb_ref "${kbRef}" not found or has no embedding for ` +
          `tenant ${tenantId}. Filling all ${maxResults} slots with similarity.`,
      );
    }
  }

  // 4. Similarity search for the remaining slots.
  // If we have a pinned entry, exclude it from similarity results to avoid
  // duplicates and fill (maxResults - 1) slots. If no pinned entry, fill all.
  const similaritySlots = maxResults - (pinnedEntry ? 1 : 0);

  let similarityResults: KbEntry[] = [];
  if (similaritySlots > 0) {
    const excludeId = pinnedEntry?.id ?? null;
    similarityResults = await runSimilaritySearch(
      db,
      tenantId,
      queryVector,
      similaritySlots,
      similarityFloor,
      excludeId,
    );
  }

  // 5. Combine: pinned entry first, then similarity results.
  const entries: KbEntry[] = [];
  if (pinnedEntry) entries.push(pinnedEntry);
  entries.push(...similarityResults);

  if (entries.length === 0) {
    return undefined;
  }

  // 6. Format into the kb_context string.
  return formatKbContext(entries);
}

// ---------------------------------------------------------------------------
// Internal types and helpers
// ---------------------------------------------------------------------------

interface KbEntry {
  id: string;
  title: string;
  content: string;
}

/**
 * Fetch a KB entry by exact title for a tenant. Only active entries with an
 * embedding are considered (ensures model consistency: entries without an
 * embedding were never indexed and are incomparable to the query vector).
 */
async function fetchByTitle(
  db: Db,
  tenantId: string,
  title: string,
): Promise<KbEntry | undefined> {
  const rows = await db.execute<{ id: string; title: string; content: string }>(sql`
    SELECT id, title, content
    FROM kb_entries
    WHERE tenant_id = ${tenantId}::uuid
      AND title = ${title}
      AND is_active = true
      AND embedding IS NOT NULL
    LIMIT 1
  `);

  if (rows.rows.length === 0) return undefined;
  return rows.rows[0]!;
}

/**
 * Run cosine similarity search using pgvector.
 *
 * The query vector is passed as a Postgres array literal (pgvector format).
 * Uses the <=> (cosine distance) operator; similarity = 1 - distance.
 *
 * Only active entries with a non-NULL embedding are searched.
 * Entries belonging to other tenants are excluded by the WHERE clause.
 *
 * Similarity scores are logged at info level for calibration visibility.
 * Both accepted and rejected candidates are logged so the floor threshold
 * can be tuned against real data.
 */
async function runSimilaritySearch(
  db: Db,
  tenantId: string,
  queryVector: number[],
  limit: number,
  floor: number,
  excludeId: string | null,
): Promise<KbEntry[]> {
  // Format the query vector as a pgvector literal: '[f1,f2,...]'
  const vectorLiteral = `[${queryVector.join(",")}]`;

  // Fetch top candidates + a few more for logging rejected ones.
  // We fetch (limit + 3) to be able to log the next few below the floor.
  const fetchLimit = limit + 3;

  type Row = { id: string; title: string; content: string; similarity: string };

  const rows = await db.execute<Row>(sql`
    SELECT id, title, content,
           (1 - (embedding <=> ${vectorLiteral}::vector)) AS similarity
    FROM kb_entries
    WHERE tenant_id = ${tenantId}::uuid
      AND is_active = true
      AND embedding IS NOT NULL
      ${excludeId ? sql`AND id != ${excludeId}::uuid` : sql``}
    ORDER BY embedding <=> ${vectorLiteral}::vector
    LIMIT ${fetchLimit}
  `);

  const accepted: KbEntry[] = [];
  const rejected: Array<{ title: string; similarity: number }> = [];

  for (const row of rows.rows) {
    const similarity = parseFloat(row.similarity);
    if (similarity >= floor) {
      if (accepted.length < limit) {
        accepted.push({ id: row.id, title: row.title, content: row.content });
      }
    } else {
      rejected.push({ title: row.title, similarity });
    }
  }

  // Log similarity scores for calibration.
  if (accepted.length > 0 || rejected.length > 0) {
    const acceptedLog = accepted
      .map((e) => `"${e.title}"`)
      .join(", ");
    const rejectedLog = rejected
      .map((r) => `"${r.title}" (${r.similarity.toFixed(3)})`)
      .join(", ");

    console.info(
      `[context-kb] similarity search tenant=${tenantId} ` +
        `floor=${floor} ` +
        (accepted.length > 0 ? `accepted=[${acceptedLog}] ` : "accepted=[] ") +
        (rejected.length > 0 ? `below-floor=[${rejectedLog}]` : "below-floor=[]"),
    );
  }

  return accepted;
}

/**
 * Format KB entries into the kb_context string injected into the draft prompt.
 *
 * Format: one entry per block, title as a header, content as the body.
 * Multiple entries are separated by a blank line. This format is compact and
 * readable both by the LLM and by humans inspecting logs.
 */
function formatKbContext(entries: KbEntry[]): string {
  return entries
    .map((e) => `[${e.title}]\n${e.content}`)
    .join("\n\n");
}
